version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet tool restore && dotnet test
  pack:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
        #- run:
        #    name: Build
        #    command: dotnet tool restore && dotnet build -c Release

workflows:
  test_pack_push:
    jobs:
            #- test
      - pack #:
              #requires:
                      #- test
