version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet tool restore && dotnet test
  pack:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
        #- run:
        #    name: Build
        #    command: dotnet tool restore && dotnet build -c Release
      - run:
          name: Install mono
          command: apt install gnupg ca-certificates && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list && apt update && apt install -f && apt install -y mono-runtime

workflows:
  test_pack_push:
    jobs:
            #- test
      - pack #:
              #requires:
                      #- test
