version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet tool restore && dotnet test
  pack:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build --configuration Release
      - run:
          name: Pack
          command: dotnet pack -c "FsToolkit.Json/FsToolkit.Json.nuspec" -p:build_number=$CIRCLE_BUILD_NU

workflows:
  test_pack_push:
    jobs:
      - test
      - pack:
              requires:
                      #   - test
