version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0.100-buster-slim
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet test
  pack:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0.100-buster-slim
    steps:
      - checkout
      - run:
          name: Pack
          command: dotnet pack -c Release

workflows:
  test_pack_push:
    jobs:
            #- test
      - pack #:
              #requires:
                      #- test
